---
- name: Install/Remove Windows Packages (URL/Local)
#  hosts: {{ host_name }}
  hosts: ad
  vars:
   file_share_path: 
   win_product_id: 
   product_state: 
#   win_user_name:
#   win_user_pass:

  tasks:
  - name: Install Something
    win_package:
      path: '{{ file_share_path }}'
      product_id: '{{ win_product_id|default(omit) }}'
      state: '{{ product_state }}'
#      user_name: '{{ win_user_name|default(omit) }}'
#      user_password: '{{ win_user_pass|default(omit) }}'
